return {
	FAST_LABEL_NONE 		= 0,
	FAST_LABEL_NEW_SERVER 	= 1,
	FAST_LABEL_NEW_ROOM 	= 2,
	FAST_LABEL_DESTROY_ROOM = 3,
	FAST_LABEL_NEW_USER 	= 4,
	FAST_LABEL_USER_LEAVE 	= 5,
	FAST_LABEL_ROOM_START 	= 6,
	FAST_LABEL_ROOM_END 	= 7,
}